<style>
    .hide { display: none; }
    .text-end { text-align: right }
</style>
<?php if ($cssRules): ?>
    <style>
        <?php foreach ($cssRules as $cssRule): ?>
        <?=$cssRule[0] . '{' . $cssRule[1] . '}'; ?>
        <?php endforeach; ?>
    </style>
<?php endif; ?>
<table>
    <?php $index = 1; ?>
    <?php foreach ($countsPerWallet as $wallet => $countPerWallet): ?>
        <tr data-wallet="<?=$wallet; ?>">
            <td class="text-center">#<?=$index; ?></td>
            <td><?=$wallet; ?></td>
            <td class="text-end">
                <a class="link-richlist-details" href="#">
                    <?=$countPerWallet['total']; ?>
                </a>
            </td>
        </tr>
        <tr class="hide">
            <td></td>
            <td class="text-end" colspan="2">
                <?php foreach ($countPerWallet['collections'] as $collectionName => $collectionData): ?>
                    <?=$collectionName; ?>: <?=$collectionData['total']; ?><br />
                <?php endforeach; ?>
            </td>
        </tr>
        <?php $index++; ?>
    <?php endforeach; ?>
</table>
<script>
const links = document.querySelectorAll('a.link-richlist-details');
if (links) {
    links.forEach(link => {
        link.addEventListener('click', (event) => {
            event.preventDefault();
            const parentRow = link.closest('tr');
            const nextRow = parentRow.nextElementSibling;
            nextRow.classList.toggle('hide');
        });
    });
}
</script>
