<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="HasMints.com">

    <link rel="apple-touch-icon" sizes="180x180" href="<?=env('URL'); ?>/assets/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=env('URL'); ?>/assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=env('URL'); ?>/assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="<?=env('URL'); ?>/assets/favicon/site.webmanifest">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">

</head>

<body class="bg-dark">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="<?=env('URL'); ?>/projects">RichLists 🤑</a>
            <?php if ($isLoggedIn): ?>
                <a class="nav-link" href="<?=env('URL'); ?>/logout">Logout</a>
            <?php else: ?>
                <a class="nav-link" href="<?=env('URL'); ?>/login">Login</a>
            <?php endif; ?>
        </div>
    </nav>

    <?php if ($isLoggedIn): ?>
        <div class="container-fluid logged-in">
            <div class="row">
                <div class="col">
                    <div class="container">
                        <?=$loggedInUser->projectName; ?>:
                        <a href="<?=env('URL'); ?>/user/<?=$loggedInUser->projectSlug; ?>">
                            Your Endpoints
                        </a>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <main>
        <?php if ($alert): ?>
            <div class="container">
                <div class="alert alert-<?=$alert['type']; ?> mt-5 text-center" role="alert">
                    <?=$alert['message']; ?>
                </div>
            </div>
        <?php endif; ?>
        <?=$content; ?>
    </main>

    <footer class="py-4">
        <p>Built by <a target="_blank" href="https://hasmints.com/">HasMints</a>.</p>
    </footer>

    <script src="<?=env('url'); ?>/assets/js/main.js"></script>
</body>

</html>
