<main role="main" class="inner cover">
    <h1 class="cover-heading">
        <em>"Need an XRPL RichList for your project?"</em>
    </h1>
    <h2>What you get</h2>
    <p class="lead">
        Dedicated webpage for holders to access the rich list.<br />
        Rich list reflects NFTs held by wallets across one or more collections within the same project.<br />
        Public API that returns the same real-time data, enabling integration into other applications.<br />
        Integration of the same table into your own website.<br />
    </p>
    <h2>$300</h2>
    <p class="lead">
        $300 Fixed fee for installation and 12 months of support. After 12 months, support is $100 per year.
    </p>
    <p class="lead">
        <a target="_blank" href="https://twitter.com/HasMints" class="btn btn-lg btn-secondary">
            Drop us a DM on X
        </a>
    </p>
</main>
