<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col col-12">
            <div class="home-money-smiley">
                🤑
            </div>
            <h1>
                <em>"Need RichListS for your project?"</em>
            </h1>
        </div>
        <div class="col col-12 col-sm-4">
            <div class="card">
                <div class="card-header">
                    <h2>Small Project</h2>
                </div>
                <div class="card-body">
                    <h3>$10 p/m</h3>
                </div>
                <div class="card-footer">
                    <p>
                        2 collections<br />
                        multi-chain *
                    </p>
                </div>
            </div>
        </div>
        <div class="col col-12 col-sm-4">
            <div class="card">
                <div class="card-header">
                    <h2>Medium Project</h2>
                </div>
                <div class="card-body">
                    <h3>$40 p/m</h3>
                </div>
                <div class="card-footer">
                    <p>
                        10 collections<br />
                        multi-chain *
                    </p>
                </div>
            </div>
        </div>
        <div class="col col-12 col-sm-4">
            <div class="card">
                <div class="card-header">
                    <h2>Large Project</h2>
                </div>
                <div class="card-body">
                    <h3>$75 p/m</h3>
                </div>
                <div class="card-footer">
                    <p>
                        25 collections<br />
                        multi-chain *
                    </p>
                </div>
            </div>
        </div>
        <div class="col col-12">
            <h2>What you get</h2>
            <p>
                Each project may have one or more chains, each representing a rich list containing multiple collections.
                This dedicated webpage allows holders to access the rich list, showcasing the NFTs held by wallets across these collections.
                Additionally, a public API is provided to fetch real-time data for integration into other applications.
                For each chain/rich list, you can obtain different API URLs in two formats: JSON for programmatic access and pure HTML format for embedding as a table on your own website.
            </p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col col-12 col-md-6">
            <ul>
                <li>Each project may have one or more chains, each representing a rich list with multiple collections.</li>
                <li>The dedicated webpage allows holders to view NFTs held across these collections.</li>
                <li>A public API provides real-time data for integration into other applications.</li>
                <li>Different API URLs are available for each chain/rich list in JSON and HTML formats.</li>
            </ul>
            <hr />
            <p>
                * Presently, our support is exclusive to XRPL. However, we are diligently striving to incorporate the following chains:
                Solana, Base, Ethereum, Binance, Polygon, Avalanche, Arbitrum, Optimism, Bitcoin and TON
            </p>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col col-12">
            <p>
                <a target="_blank" href="https://twitter.com/HasMints" class="btn btn-lg btn-primary">
                    Drop us a DM on X if you're interested
                </a>
            </p>
        </div>
    </div>
</div>
