<div class="container my-5">
    <div class="row">
        <div class="col col-12">
            <div class="home-money-smiley">
                🤑
            </div>
            <h1>
                <em>"Need a RichList for your project?"</em>
            </h1>
            <h2>What you get</h2>
            <p>
                Dedicated webpage for holders to access the rich list.
                Rich list reflects NFTs held by wallets across one or more collections within the same project.
                Public API that returns the same real-time data, enabling integration into other applications.
                Integration of the same table into your own website.
            </p>
            <h2>$300</h2>
            <p>
                $300 Fixed fee for installation and 12 months of support. After 12 months, support is $100 per year.
            </p>
            <p>
                <a target="_blank" href="https://twitter.com/HasMints" class="btn btn-lg btn-primary">
                    Drop us a DM on X
                </a>
            </p>
        </div>
    </div>
</div>
