<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col col-12">
            <h1>
                Login
            </h1>
        </div>
        <div class="col col-12 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <form id="login" method="post" action="login">
                        <div class="form-group my-3">
                            <label for="email" class="my-2">E-mail address</label>
                            <input
                                type="email"
                                name="email"
                                class="form-control"
                                id="email"
                                placeholder="E-mail"
                            />
                            <?=parse_form_errors('email', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="password" class="my-2">Password</label>
                            <input
                                type="password"
                                name="password"
                                class="form-control"
                                id="password"
                            />
                            <?=parse_form_errors('password', $formErrors); ?>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
