<div class="container">
    <div class="row justify-content-center">
        <div class="col col-10">
            <h1>
                All RichLists
            </h1>
        </div>
    </div>
    <div class="row">
        <?php foreach ($users as $user): /* @var $user \App\Models\User */ ?>
            <div class="col col-12 col-xs-12 col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-header">
                        <h2><?=$user->projectName; ?></h2>
                    </div>
                    <div class="card-body">
                        <?php if ($user->hasCollectionsOnChain('xrpl')): ?>
                            <a class="btn btn-primary" href="<?=env('URL'); ?>/project/<?=$user->projectSlug; ?>/xrpl">
                                XRPL RichList
                            </a>
                        <?php endif; ?>
                        <?php if ($user->hasCollectionsOnChain('solana')): ?>
                            <a class="btn btn-primary" href="<?=env('URL'); ?>/project/<?=$user->projectSlug; ?>/solana">
                                XRPL RichList
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
