<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col col-12">
            <h1>
                Register
            </h1>
        </div>
        <div class="col col-12 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <form id="register" method="post" action="register">
                        <div class="form-group my-3">
                            <label for="email" class="my-2">Email address</label>
                            <input
                                type="email"
                                name="email"
                                class="form-control <?=$formErrors && isset($formErrors['email']) ? 'is-invalid' : ''; ?>"
                                value="<?=$formValidatedValues && isset($formValidatedValues['email']) ? $formValidatedValues['email'] : ''; ?>"
                                id="email"
                                placeholder="Your e-mail"
                            />
                            <?=parse_form_errors('email', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="project_name" class="my-2">Project Name</label>
                            <input
                                type="text"
                                name="project_name"
                                class="form-control <?=$formErrors && isset($formErrors['project_name']) ? 'is-invalid' : ''; ?>"
                                value="<?=$formValidatedValues && isset($formValidatedValues['project_name']) ? $formValidatedValues['project_name'] : ''; ?>"
                                id="project_name"
                                placeholder="Project Name"
                            />
                            <?=parse_form_errors('project_name', $formErrors); ?>
                        </div>
                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
