<div class="container">
    <div class="row justify-content-center">
        <div class="col col-10">
            <h1>
                <a href="<?=env('URL'); ?>/project/<?=$user->projectSlug; ?>"><?=$projectName; ?></a> RichList on <?=$chain; ?>
            </h1>
        </div>
    </div>

    <ul class="nav nav-tabs">
        <?php if ($user->hasCollectionsOnChain('base')): ?>
            <li class="nav-item">
                <a
                    href="<?=env('URL'); ?>/project/<?=$user->projectSlug; ?>/base"
                    class="nav-link <?=(strtolower($chain) === 'base' ? 'active' : ''); ?>"
                    aria-current="page"
                >
                    Base
                </a>
            </li>
        <?php endif; ?>
        <?php if ($user->hasCollectionsOnChain('xrpl')): ?>
            <li class="nav-item">
                <a
                    href="<?=env('URL'); ?>/project/<?=$user->projectSlug; ?>/xrpl"
                    class="nav-link <?=(strtolower($chain) === 'xrpl' ? 'active' : ''); ?>"
                    aria-current="page"
                >
                    XRPL
                </a>
            </li>
        <?php endif; ?>
        <?php if ($user->hasCollectionsOnChain('ethereum')): ?>
            <li class="nav-item">
                <a
                    href="<?=env('URL'); ?>/project/<?=$user->projectSlug; ?>/ethereum"
                    class="nav-link <?=(strtolower($chain) === 'ethereum' ? 'active' : ''); ?>"
                    aria-current="page"
                >
                    Ethereum
                </a>
            </li>
        <?php endif; ?>
    </ul>


    <div class="row justify-content-center row-richlist">
        <div class="col col-12 col-xs-10">
            <div class="table-responsive">
                <table class="table">
                    <?php $index = 1; ?>
                    <?php foreach ($countsPerWallet as $wallet => $countPerWallet): ?>
                        <tr data-wallet="<?=$wallet; ?>">
                            <td width="100px" class="text-center">#<?=$index; ?></td>
                            <td>
                                <span class="wallet-full"><?=$wallet; ?></span>
                                <span class="wallet-trimmed"><?=substr($wallet, 0, 16); ?>..</span>
                            </td>
                            <td class="text-end">
                                <a class="btn btn-primary btn-richlist-details" href="#">
                                    <?=$countPerWallet['total']; ?>
                                </a>
                            </td>
                        </tr>
                        <tr class="hide">
                            <td></td>
                            <td class="text-end" colspan="2">
                                <?php foreach ($countPerWallet['collections'] as $collectionName => $collectionData): ?>
                                    <?=$collectionName; ?>: <?=$collectionData['total']; ?><br />
                                <?php endforeach; ?>
                            </td>
                        </tr>
                        <?php $index++; ?>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
