<div class="container">
    <div class="row justify-content-center">
        <div class="col col-10">
            <h1>
                <?=$projectName; ?> <a href="<?=env('URL'); ?>/projects">RichLists</a>
            </h1>
        </div>
    </div>
    <div class="row justify-content-center row-richlist">
        <?php if ($user->hasCollectionsOnChain('xrpl')): ?>
            <div class="col col-12 col-xs-12 col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-header">
                        <h2>XRPL</h2>
                    </div>
                    <div class="card-body">
                        <?php foreach ($user->getCollectionsForChain('xrpl') as $collection): ?>
                            <?=$collection->name; ?><br />
                        <?php endforeach; ?>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-primary" href="<?=env('URL'); ?>/project/<?=$user->projectSlug; ?>/xrpl">
                            RichList
                        </a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
