<div class="container">
    <div class="row justify-content-center">
        <div class="col col-10">
            <h1>
                <?=$projectName; ?> RichList
            </h1>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col col-10">
            <div class="table-responsive">
                <table class="table">
                    <?php $index = 1; ?>
                    <?php foreach ($countsPerWallet as $wallet => $countPerWallet): ?>
                        <tr>
                            <td>#<?=$index; ?></td>
                            <td><?=$wallet; ?></td>
                            <td class="text-end">
                                <a class="btn btn-primary" href="#">
                                    <?=$countPerWallet['total']; ?>
                                </a>
                            </td>
                        </tr>
                        <tr class="hide">
                            <td></td>
                            <td class="text-end" colspan="2">
                                <?php foreach ($countPerWallet['collections'] as $collectionName => $collectionData): ?>
                                    <?=$collectionName; ?>: <?=$collectionData['total']; ?><br />
                                <?php endforeach; ?>
                            </td>
                        </tr>
                        <?php $index++; ?>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
