<div class="container">
    <div class="row justify-content-center">
        <div class="col col-10">
            <h1>
                <?=$projectName; ?> RichList XRPL
            </h1>
        </div>
    </div>
    <div class="row justify-content-center row-richlist">
        <div class="col col-12 col-xs-10">
            <div class="table-responsive">
                <table class="table">
                    <?php $index = 1; ?>
                    <?php foreach ($countsPerWallet as $wallet => $countPerWallet): ?>
                        <tr data-wallet="<?=$wallet; ?>">
                            <td class="text-center">#<?=$index; ?></td>
                            <td>
                                <span class="wallet-full"><?=$wallet; ?></span>
                                <span class="wallet-trimmed"><?=substr($wallet, 0, 16); ?>..</span>
                            </td>
                            <td class="text-end">
                                <a class="btn btn-primary btn-richlist-details" href="#">
                                    <?=$countPerWallet['total']; ?>
                                </a>
                            </td>
                        </tr>
                        <tr class="hide">
                            <td></td>
                            <td class="text-end" colspan="2">
                                <?php foreach ($countPerWallet['collections'] as $collectionName => $collectionData): ?>
                                    <?=$collectionName; ?>: <?=$collectionData['total']; ?><br />
                                <?php endforeach; ?>
                            </td>
                        </tr>
                        <?php $index++; ?>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
