<div class="container">
    <div class="row justify-content-center">
        <div class="col col-10">
            <h1>
                User <?=$projectName; ?>
            </h1>
        </div>
    </div>
    <div class="row justify-content-center">
        <h2>API Links for JSON and HTML output</h2>
        <h3>Incorporate these raw outputs into your app, site, or tool.</h3>

        <div class="col col-10">
            <div class="card">
                <div class="card-body">
                    <?php if ($user->hasCollectionsOnChain('xrpl')): ?>
                        <?php
                        foreach (['json', 'html'] as $dataType) {
                            $apiField = [
                                'id' => 'xrpl-' . $dataType,
                                'title' => 'XRPL ' . strtoupper($dataType),
                                'url' => (env('URL') . '/' . $dataType. '/' . $user->projectSlug . '/xrpl/' . $user->token),
                            ];
                            include('templates/views/website/partials/user-disabled-api-field.phtml');
                        }
                        ?>
                    <?php endif; ?>
                    <?php if ($user->hasCollectionsOnChain('ethereum')): ?>
                        <?php
                        foreach (['json', 'html'] as $dataType) {
                            $apiField = [
                                'id' => 'ethereum-' . $dataType,
                                'title' => 'Ethereum ' . strtoupper($dataType),
                                'url' => (env('URL') . '/' . $dataType. '/' . $user->projectSlug . '/ethereum/' . $user->token),
                            ];
                            include('templates/views/website/partials/user-disabled-api-field.phtml');
                        }
                        ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<!--    <div class="row justify-content-center">-->
<!--        <div class="col col-10">-->
<!--            <h3>-->
<!--                Example usage of HTML API URL in an iFrame-->
<!--            </h3>-->
<!--            <div class="card">-->
<!--                <div class="card-body text-start">-->
<!--                    <pre>-->
<!--                        <code>-->
<?php //=$exampleCodeHtml; ?>
<!--                        </code>-->
<!--                    </pre>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="row justify-content-center">-->
<!--        <div class="col col-10">-->
<!--            <h3>-->
<!--                Example usage of JSON API URL - render table via JS-->
<!--            </h3>-->
<!--            <div class="card">-->
<!--                <div class="card-body text-start">-->
<!--                    <pre>-->
<!--                        <code>-->
<?php //=$exampleCodeJson; ?>
<!--                        </code>-->
<!--                    </pre>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
</div>
